name: quotation-app
quotations-bucket-url: s3://quotations
quotations-queue: QuotationsQueue

aws:
  s3:
    region: sa-east-1
    endpoint: http://localhost:4566
  sqs:
    region: sa-east-1
    endpoint: http://localhost:4566/000000000000
    access-key: quotations
    secret-key: quotations
